export default function PrivacyPolicy() {
    return (
        <main className="policy">

            <header className="policy-header">
                <h1 className="policy-heading">Privacy Notice</h1>
                <p className="policy-date">Effective date: April 3, 2023</p>
            </header>

            <p>CopyAI, Inc. (“Copy.AI,” “we,” “us,” and “our”) provides an AI powered tool to assist our customers in writing copy. This Privacy Notice is designed to help you understand how we collect, use, and share your personal information and to help you understand and exercise your privacy rights.</p>
            <p>Please read these Terms of Service (the “Terms”) and our Privacy Notice (“Privacy Notice”) carefully because they govern your use of the CopyAI, Inc. (“Copy.AI”) website located at www.copy.ai (the “Site”), Copy.AI’s copy content generation services, and any copy content generated by Copy.AI’s services for you based on your User Content (defined below) (“Generated Content”). To make these Terms easier to read, the Site, our services, and the Generated Content are collectively called the “Services.”</p>

            <h3>1.Scope.</h3>
            <p>This Privacy Notice applies to personal information processed by us on our website, our services offered via the website, and our related online and offline offerings. To make this Privacy Notice easier to read, our websites, our services offered via the website, and our related offerings are collectively called “Services.”</p>

            <h3>2. Change to our privacy notice</h3>
            <p>We may revise this Privacy Notice from time to time in our sole discretion. If there are any material changes to this Privacy Notice, we will notify you and require you to accept them before you may continue to use the Services.</p>

            <h3>3. Personal information we collect</h3>
            <p>The categories of personal information we collect depend on how you interact with us, our Services and the requirements of applicable law. We collect information that you provide to us, information we obtain automatically when you use our Services, and information from other sources such as third-party services and organizations, as described below.</p>
            <p><strong>A. Information You Provide to Us Directly</strong></p>

            <p>We may collect the following personal information that you provide to us.</p>

            <p>• Account Creation. We may collect information when you create an account, such as name and email address.</p>
            <p>• Purchases. We may collect personal information and details associated with your purchases, including payment information. In some cases, you may need to provide us with additional information to verify your identity before completing a transaction. Any payments made via our Services are processed by third-party payment processors. We do not directly collect or store any payment card information entered through our Services, but we may receive information associated with your payment card information (e.g., your billing details).</p>
            <p>• Your Communications with Us. We may collect personal information, such as email address, phone number, or mailing address when you request information about our Services, register for our newsletter or marketing, request customer or technical support, apply for a job or otherwise communicate with us.</p>
            <p>• Surveys. We may contact you to participate in surveys. If you decide to participate, you may be asked to provide certain information which may include personal information.</p>
            <p>• Interactive Features. We and others who use our Services may collect personal information that you submit or make available through our interactive features (e.g., collaboration tools, messaging and chat features, commenting functionalities, forums, blogs, and social media pages). Any information you provide on the public sections of these features will be considered “public,” unless otherwise required by applicable law, and is not subject to the privacy protections referenced herein.</p>
            <p>• Sweepstakes or Contests. We may collect personal information you provide for any sweepstakes or contests that we offer. In some jurisdictions, we are required to publicly share information of sweepstakes and contest winners.</p>
            <p>• Conferences, Trade Shows, and Other Events. We may collect personal information from individuals when we attend conferences, trade shows, and other events.</p>
            <p>• Business Development and Strategic Partnerships. We may collect personal information from individuals and third parties to assess and pursue potential business opportunities.</p>
            <p>• Job Applications. We may post job openings and opportunities on our Services. If you reply to one of these postings by submitting your application, CV and/or cover letter to us, we will collect and use your information to assess your qualifications.</p>

            <p><strong>B. Information Collected Automatically</strong></p>
            <p>We may collect personal information automatically when you use our Services:</p>
            <p>• Automatic Data Collection. We may collect certain information automatically when you use our Services, such as your Internet protocol (IP) address, user settings, MAC address, cookie identifiers, mobile carrier, mobile advertising and other unique identifiers, browser or device information, location information (including approximate location derived from IP address), and Internet service provider. We may also automatically collect information regarding your use of our Services, such as pages that you visit before, during and after using our Services, information about the links you click, the types of content you interact with, the frequency and duration of your activities, and other information about how you use our Services. In addition, we may collect information that other people provide about you when they use our Services, including information about you when they tag you.</p>
            <p>• Cookies, Pixel Tags/Web Beacons, and Other Technologies. We, as well as third parties that provide content, advertising, or other functionality on our Services, may use cookies, pixel tags, local storage, and other technologies (“Technologies”) to automatically collect information through your use of our Services.</p>
            <p>• Cookies. Cookies are small text files placed in device browsers that store preferences and facilitate and enhance your experience.</p>
            <p>• Pixel Tags/Web Beacons. A pixel tag (also known as a web beacon) is a piece of code embedded in our Services that collects information about engagement on our Services. The use of a pixel tag allows us to record, for example, that a user has visited a particular web page or clicked on a particular advertisement. We may also include web beacons in e-mails to understand whether messages have been opened, acted on, or forwarded.</p>
            <p>Our uses of these Technologies fall into the following general categories:</p>
            <p>• Operationally Necessary. This includes Technologies that allow you access to our Services, applications, and tools that are required to identify irregular website behavior, prevent fraudulent activity and improve security or that allow you to make use of our functionality;</p>

            <p>• Performance-Related. We may use Technologies to assess the performance of our Services, including as part of our analytic practices to help us understand how individuals use our Services (see Analytics below);</p>
            <p>• Functionality-Related. We may use Technologies that allow us to offer you enhanced functionality when accessing or using our Services. This may include identifying you when you sign into our Services or keeping track of your specified preferences, interests, or past items viewed;</p>
            <p>• Advertising- or Targeting-Related. We may use first party or third-party Technologies to deliver content, including ads relevant to your interests, on our Services or on third-party websites.</p>
            <p>See Section 6 below to understand your choices regarding these Technologies.</p>
            <p>• Analytics. We may use Technologies and other third-party tools to process analytics information on our Services. Some of our analytics partners include Google Analytics. For more information, please visit Google Analytics’ Privacy Notice. To learn more about how to opt-out of Google Analytics’ use of your information on our website, please click here.</p>
            <p>• Social Media Platforms. Our Services may contain social media buttons (that might include widgets such as the “share this” button or other interactive mini programs). These features may collect your IP address, which page you are visiting on our Services, and may set a cookie to enable the feature to function properly. Your interactions with these platforms are governed by the Privacy Notice of the company providing it.</p>


            <p><strong>C. Information Collected from Other Sources</strong></p>
            <p>We may obtain information about you from other sources, including through third-party services and organizations. For example, if you access our Services through a third-party application, such as an app store, a third-party login service, or a social networking site, we may collect information about you from that third-party application that you have made available via your privacy settings.</p>
            <h3>4. How we use your information </h3>
            <p>We use your information for a variety of business purposes, including to provide our Services, for administrative purposes, and to market our products and Services, as described below.</p>

            <p><strong>A. Provide Our Services</strong></p>
            <p>We use your information to fulfil our contract with you and provide you with our Services, such as:</p>
            <p>• Managing your information and accounts;</p>
            <p>• Providing access to certain areas, functionalities, and features of our Services;</p>
            <p>• Answering requests for customer or technical support;</p>
            <p>• Communicating with you about your account, activities on our Services, and policy changes;</p>
            <p>• Processing your financial information and other payment methods for products or Services purchased;</p>
            <p>• Processing applications if you apply for a job, we post on our Services; and</p>
            <p>• Allowing you to register for events.</p>

            <p><strong>B. Administrative Purposes</strong></p>
            <p>• Pursuing our legitimate interests such as direct marketing, research and development (including marketing research), network and information security, and fraud prevention;</p>
            <p>• Measuring interest and engagement in our Services;</p>

            <p>• Short-term, transient use, such as contextual customization of ads;</p>
            <p>• Improving, upgrading or enhancing our Services;</p>
            <p>• Developing new products and Services;</p>
            <p>• Ensuring internal quality control and safety;</p>
            <p>• Authenticating and verifying individual identities;</p>
            <p>• Debugging to identify and repair errors with our Services;</p>
            <p>• Auditing relating to interactions, transactions and other compliance activities;</p>
            <p>• Enforcing our agreements and policies; and</p>
            <p>• Complying with our legal obligations.</p>


            <p><strong>C. Marketing and Advertising our Products and Services</strong></p>
            <p>We may use personal information to tailor and provide you with content and advertisements. We may provide you with these materials as permitted by applicable law.</p>
            <p>Some of the ways we may market to you include email campaigns, custom audiences advertising, and “interest-based” or “personalized advertising,” including through cross-device tracking.</p>
            <p>If you have any questions about our marketing practices or if you would like to opt out of the use of your personal information for marketing purposes, you may contact us at any time as set forth below.</p>

            <p><strong>D. Other Purposes</strong></p>
            <p>We also use your information for other purposes as requested by you or as permitted by applicable law.</p>
            <p>• Consent. We may use personal information for other purposes that are clearly disclosed to you at the time you provide personal information or with your consent.</p>
            <p>• De-identified and Aggregated Information. We may use personal information and other information about you to create de-identified and/or aggregated information, such as de-identified demographic information, de-identified location information, information about the device from which you access our Services, or other analyses we create.</p>
            <p>• Share Content with Friends or Colleagues. Our Services may offer various tools and functionalities. For example, we may allow you to provide information about your friends or colleagues through our referral services. Our referral services may allow you to forward or share certain content with a friend or colleague, such as an email inviting your friend to use our Services.</p>

            <h3>5.How we disclose your information</h3>

            <p>We disclose your information to third parties for a variety of business purposes, including to provide our Services, to protect us or others, or in the event of a major business transaction such as a merger, sale, or asset transfer, as described below.</p>
            <p><strong>A. Disclosures to Provide our Services</strong></p>

            <p>The categories of third parties with whom we may share your information are described below.
                • Service Providers. We may share your personal information with our third-party service providers who use that information to help us provide our Services. This includes service providers that provide us with IT support, hosting, payment processing, customer service, and related services.
                •   Other Copy.AI Users at Your Direction. When you use the Services, including Copy.AI’s interactive features, you may direct Copy.AI to share certain information with other Copy.AI users. This information can include personal information about yourself and details about your work and your use of the Services.
                • Business Partners. We may share your personal information with business partners to provide you with a product or service you have requested. We may also share your personal information to business partners with whom we jointly offer products or services.
                • Affiliates. We may share your personal information with our company affiliates, for our administrative purposes including activities such as IT management, for them to provide services to you, or to support and supplement the Services we provide.
                • Advertising Partners. We may share your personal information with third-party advertising partners. These third-party advertising partners may set Technologies and other tracking tools on our Services to collect information regarding your activities and your device (e.g., your IP address, cookie identifiers, page(s) visited, location, time of day). These advertising partners may use this information (and similar information collected from other services) for purposes of delivering personalized advertisements to you when you visit digital properties within their networks. This practice is commonly referred to as “interest-based advertising” or “personalized advertising.”
                • APIs/SDKs. We may use third-party application program interfaces (“APIs”) and software development kits (“SDKs”) as part of the functionality of our Services. For more information about our use of APIs and SDKs, please contact us as set forth below.
            </p>

            <p><strong>B. Disclosures to Protect Us or Others</strong></p>
            <p>We may access, preserve, and disclose any information we store associated with you to external parties if we, in good faith, believe doing so is required or appropriate to: comply with law enforcement or national security requests and legal process, such as a court order or subpoena; protect your, our, or others’ rights, property, or safety; enforce our policies or contracts; collect amounts owed to us; or assist with an investigation or prosecution of suspected or actual illegal activity.</p>

            <p><strong>C. Disclosure in the Event of Merger, Sale, or Other Asset Transfers</strong></p>
            <p>If we are involved in a merger, acquisition, financing due diligence, reorganization, bankruptcy, receivership, purchase or sale of assets, or transition of service to another provider, your information may be sold or transferred as part of such a transaction, as permitted by law and/or contract.</p>

            <h3>6. YOUR PRIVACY CHOICES AND RIGHTS</h3>
            <p>Your pPrivacy Choices. The privacy choices you may have about your personal information are determined by applicable law and are described below.
                • Email Communications. If you receive an unwanted email from us, you can use the unsubscribe link found at the bottom of the email to opt out of receiving future emails. Note that you will continue to receive transaction-related emails regarding products or Services you have requested. We may also send you certain non-promotional communications regarding us and our Services, and you will not be able to opt out of those communications (e.g., communications regarding our Services or updates to our Terms of Service or this Privacy Notice).
                • “Do Not Track.” Do Not Track (“DNT”) is a privacy preference that users can set in certain web browsers. Please note that we do not respond to or honor DNT signals or similar mechanisms transmitted by web browsers.
                • Cookies and Interest-Based Advertising. You may stop or restrict the placement of Technologies on your device or remove them by adjusting your preferences as your browser or device permits. However, if you adjust your preferences, our Services may not work properly. Please note that cookie-based opt-outs are not effective on mobile applications. However, you may opt-out of personalized advertisements on some mobile applications by following the instructions for Android, iOS and others.
                The online advertising industry also provides websites from which you may opt out of receiving targeted ads from data partners and other advertising partners that participate in self-regulatory programs. You can access these and learn more about targeted advertising and consumer choice and privacy by visiting the Network Advertising Initiative, the Digital Advertising Alliance, the European Digital Advertising Alliance, and the Digital Advertising Alliance of Canada.
                Please note you must separately opt out in each browser and on each device.
                Your Privacy Rights. In accordance with applicable law, you may have the right to:
                • Access Personal Information about you, including: (i) confirming whether we are processing your personal information; (ii) obtaining access to or a copy of your personal information;
                • Request Deletion, Anonymization or Blocking of your personal information when processing is based on your consent or when processing is unnecessary, excessive or noncompliant;
                • Request Restriction of or Object to our processing of your personal information;
                • Withdraw Your Consent to our processing of your personal information. If you refrain from providing personal information or withdraw your consent to processing, some features of our Service may not be available;
                • Request a portable copy of your personal information;
                • Be Informed about third parties with which your personal information has been shared; and
                • Request the Review of decisions taken exclusively based on automated processing if that could affect data subject rights.
                If you would like to exercise any of these rights, please contact us as set forth in Section 15 below. We will process such requests in accordance with applicable laws.
            </p>



            <h3>7. SECURITY OF YOUR INFORMATION</h3>
            <p>
                We take steps to ensure that your information is treated securely and in accordance with this Privacy Notice. Unfortunately, no system is 100% secure, and we cannot ensure or warrant the security of any information you provide to us. To the fullest extent permitted by applicable law, we do not accept liability for unauthorized disclosure.
                By using our Services or providing personal information to us, you agree that we may communicate with you electronically regarding security, privacy, and administrative issues relating to your use of our Services. If we learn of a security system’s breach, we may attempt to notify you electronically by posting a notice on our Services, by mail or by sending an email to you.
            </p>



            <h3>8. INTERNATIONAL DATA TRANSFERS</h3>
            <p>All information processed by us may be transferred, processed, and stored anywhere in the world, including, but not limited to, the United States or other countries, which may have data protection laws that are different from the laws where you live. We endeavor to safeguard your information consistent with the requirements of applicable laws.</p>

            <h3>9. RETENTION OF PERSONAL INFORMATION</h3>
            <p>We store the personal information we collect as described in this Privacy Notice for as long as you use our Services or as necessary to fulfill the purpose(s) for which it was collected, provide our Services, resolve disputes, establish legal defenses, conduct audits, pursue legitimate business purposes, enforce our agreements, and comply with applicable laws.</p>

            <h3>10. SUPPLEMENTAL NOTICE FOR CALIFORNIA RESIDENTS</h3>
            <p>This Supplemental California Privacy Notice only applies to our processing of personal information that is subject to the California Consumer Privacy Act of 2018 (“CCPA”). The CCPA provides California residents with the right to know what categories of personal information Copy.AI has collected about them and whether Copy.AI disclosed that personal information for a business purpose (e.g., to a service provider) in the preceding 12 months. California residents can find this information below: The categories of sources from which we collect personal information and our business and commercial purposes for using personal information are set forth above.
                Additional Privacy Rights for California Residents
                “Sales” of Personal Information under the CCPA. For purposes of the CCPA, Copy.AI does not “sell” personal information, nor do we have actual knowledge of any “sale” of personal information of minors under 16 years of age.
                Non-Discrimination. California residents have the right not to receive discriminatory treatment by us for the exercise of their rights conferred by the CCPA.
                Authorized Agent. Only you, or someone legally authorized to act on your behalf, may make a verifiable consumer request related to your personal information. To designate an authorized agent, please contact us as set forth below.
                Verification. When you make a request, we will ask you to provide sufficient information that allows us to reasonably verify you are the person about whom we collected personal information or an authorized representative, which may include confirming the email address associated with any personal information we have about you.
                If you are a California resident and would like to exercise any of your rights under the CCPA, please contact us as set forth below. We will process such requests in accordance with applicable laws.
                California Shine the Light. The California “Shine the Light” law permits users who are California residents to request and obtain from us once a year, free of charge, a list of the third parties to whom we have disclosed their personal information (if any) for their direct marketing purposes in the prior calendar year, as well as the type of personal information disclosed to those parties.
            </p>


            <h3>11. SUPPLEMENTAL NOTICE FOR NEVADA RESIDENTS</h3>
            <p>If you are a resident of Nevada, you have the right to opt-out of the sale of certain personal information to third parties who intend to license or sell that personal information. You can exercise this right by contacting us as set forth below with the subject line “Nevada Do Not Sell Request” and providing us with your name and the email address associated with your account. Please note that we do not currently sell your personal information as sales are defined in Nevada Revised Statutes Chapter 603A.</p>


            <h3>12. CHILDREN’S INFORMATION</h3>
            <p>The Services are not directed to children under 13 (or other age as required by local law), and we do not knowingly collect personal information from children. If you learn that your child has provided us with personal information without your consent, you may contact us as set forth below. If we learn that we have collected a child’s personal information in violation of applicable law, we will promptly take steps to delete such information.</p>


            <h3>13. THIRD-PARTY WEBSITES/APPLICATIONS</h3>
            <p>The Services may contain links to other websites/applications and other websites/applications may reference or link to our Services. These third-party services are not controlled by us. We encourage our users to read the privacy policies of each website and application with which they interact. We do not endorse, screen or approve, and are not responsible for, the privacy practices or content of such other websites or applications. Providing personal information to third-party websites or applications is at your own risk.</p>

            <h3>14. SUPERVISORY AUTHORITY</h3>
            <p>If you are located in the European Economic Area, Switzerland, the United Kingdom or Brazil, you have the right to lodge a complaint with a supervisory authority if you believe our processing of your personal information violates applicable law.</p>



            {/*             
            <header className="policy-header">
                <p className="policy-subheading">Privacy Policy</p>
                <h1 className="policy-heading">We care about your privacy</h1>
                <p className="policy-header-text">Thank you for choosing us. This Privacy Policy is designed to help you understand how we collect, use, and safeguard your information when you use our dating app monitoring service. By using our platform, you agree to the terms outlined in this policy.</p>
            </header>

            <h2 className="policy-h2">Information We Collect</h2>

            <h4 className="policy-h4">1. Personal Information</h4>
            <p className="policy-text">
                When you register for an account, we may collect personal information, including your name, email address, and payment details for premium services.
             </p>
          

             <h4 className="policy-h4">2. Monitoring Data</h4>
            <p className="policy-text">
                Our platform utilizes AI algorithms to monitor your partner's activity on dating apps. This includes analyzing profile information, interactions, and behavioral patterns to provide you with relevant insights.
            </p>
          

             <h3 className="policy-h4">3. Device Information</h3>
            <p className="policy-text">
            We collect information about the devices you use to access our platform, such as device type, operating system, and browser details, to enhance the user experience and ensure compatibility.
            </p>
          
          <h2 className="plicy-h2">How We Use Your Information</h2>
          <h4 className="policy-h4">1. Service Provision</h4>
          <p className="policy-text">Your personal information is used to create and manage your account, facilitate transactions for premium services, and provide customer support.</p>

          <h4 className="policy-h4">2. Data Analysis</h4>
          <p className="policy-text">We analyze monitoring data to generate reports and insights for you, helping you make informed decisions about your relationship.</p>

          <h4 className="policy-h4">3. Communication</h4>
          <p className="policy-text">We may use your email address to send important notifications, updates, or promotional content related to our services. You can opt-out of promotional emails at any time.</p>


            <h3 className="policy-h3">Information Sharing</h3>

            <h4 className="policy-h4">1. Third-Party Services</h4>
            <p className="policy-text">
            We may share non-personal and aggregated information with third-party service providers for analytics, marketing, and other business purposes. This information does not identify you personally.
            </p>

            <h4 className="policy-h4">2. Legal Compliance</h4>
            <p className="policy-text">
            We may disclose your information to comply with applicable laws, regulations, or legal requests.
            </p>

            <h3 className="policy-h3">Data Security</h3>
            <p className="policy-text">We prioritize the security of your data and employ industry-standard measures, including encryption and access controls, to protect against unauthorized access, disclosure, or alteration.</p>

            <h3 className="policy-h3">Your Choices</h3>
            <p className="policy-text">You can manage your account settings, including communication preferences, through the platform. You have the option to deactivate your account at any time.</p>

            <h2 className="policy-h2">Updates to this Privacy Policy</h2>
            <p className="policy-text">We may update this Privacy Policy to reflect changes in our practices. The most recent version will be available on our website.</p>
*/}
        </main>
    )
}