export default function RefundPolicy() {
    return (
        <main className="policy">
        
        <header className="policy-header">
        <h1 className="policy-heading">Payment and Delivery Conditions Refunds Policy</h1>
        <p className="policy-date">Effective date: April 3, 2023</p>
    </header>

    <p> Please read these Terms of Service (the “Terms”) and our Privacy Notice (“Privacy Notice”) carefully because
        they
        govern your use of the Viralink, Inc. (“Viral.ink”) website located at www.copy.ai (the “Site”), Viralink’s copy
        content generation services, and any copy content generated by Copy.AI’s services for you based on your User
        Content
        (defined below) (“Generated Content”). To make these Terms easier to read, the Site, our services, and the
        Generated
        Content are collectively called the “Services.”
    </p>

    <h3>Payment Methods</h3>

    <p>
        Buying on SocialsGrow is easy for our users. We have various payment processing options so that our customers
        can pay in the most convenient method possible. We secure payment details in all possible ways, including using
        secure
        servers that will keep all information you share with us safe from hackers. Payments are to be made in American
        dollars unless otherwise specified.
        We accept the following payment methods:
        Mastercard
        Visa
        American Express
        Discover
        Google Pay
        Apple Pay
        Should you have further queries about the services we offer, please reach out to us. We pride ourselves on how
        easy
        it is to use our website and purchase our services. High-level customer service is our main goal. If you are not
        entirely satisfied for any reason, let us know so that we can try to devise a solution to make it right.
    </p>
    <h3>Credit Card Information</h3>

    <p>
        When you elect to pay for one of our services or products through the site’s secure credit card processing
        facility,
        we will need your credit card details, along with your name, and email address. We need those details so we can
        send
        you your order along with a receipt and tax invoice.
        We protect all credit card information that we receive through our online transactions. We use SSL (secure
        sockets
        layer) software which encrypts the information your computer sends us as it is transferred to our servers. For
        SSL
        certificate details, click on the padlock icon on our payment page. Our state-of-the-art servers are located in
        the
        UK.
    </p>
    <h3>Delivery</h3>

    <p>

        The delivery process will begin instantly within 24 hours of you placing your order and SocialsGrow processing
        the
        payment. Take note that in order to fulfill your request, we need an accurate link to a social media account, as
        well as video, tweet, or post information, etc. if applicable.
        Expect smaller deliveries within a day or two of placing the order, while larger orders may take a couple of
        days.
        For more explicit details regarding how long your order will take, please look at the specific number of subs,
        likes, comments, etc. you are buying.
        Conditions may exist wherein we will be unable to process your order. Those might include if we cannot process
        your
        credit card payment or other payment method, if you sent us invalid social media links, or if you have a private
        account that we’re unable to access. Under those circumstances, we will attempt to contact you so you have the
        opportunity to correct the issue if you wish.
    </p>
    <h3> Refunds and Refills</h3>
    <p>
        In certain situations, we are willing to offer refunds. That might be if we were unable to provide you with the
        service you requested or if we gave you the wrong service. If you do not contact us and let us know about any
        problem or inaccuracy, then we will assume the order was completed as requested.
        If you would prefer a refill of the social media engagement you ordered, then we will attempt delivery for you
        again
        instead of furnishing you with a refund.
        How Are a Refund and Refill Different from One Another?
        A refund is a chance for you to get back the total money you paid us. We can do that in two scenarios:
        The delivered item does not match the website description
        The delivery did not start within ten days of you placing the order
        By contract, a refill is a reimbursement. If a person ordered a service of 100 subscribers, for instance, and
        those
        were delivered, and then within a week 15 of those were “cut off” or dropped, we would refill them at no further
        cost to the customer.
        Please note that there is no automatic refill option. You can contact customer support and we will refill your
        lost
        subscribers or engagement numbers. The refill will begin within the following 24-48 hours. If you do not see
        your
        numbers increase to the appropriate amount, please reach out to customer support again. We ask that you please
        send
        us evidence of your paid-for engagement numbers dropping off, such as a screenshot, so that we can verify your
        claim’s veracity.
        You have thirty (30) days to request any refills or refunds.
    </p>


        </main>
    )
}